service: serverless-stepf-services-integrations
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-1

functions:
  handler:
    handler: functions/handler.handler
